### ISSUE TITLE
No annotation for variable arguments

### ISSUE THREAD

**Issue by asafyev** [ombre42/jrobotremoteserver#28]
This kind of keyword results in an error: "Keyword 'Remote.Click One Of' expected 1 argument, got 2."

@RobotKeyword("Click one of elements with ids.")
@ArgumentNames({"ids"})
public void clickOneOf(String... ids) {
     ...
}

Is there a solution?

**Comment by pekkaklarck** [comment]
Have you tried `*ids` instead of `ids`? I'm not sure about this context, but that's generally the syntax to tell Robot that a keyword accepts variable number of arguments.

**Comment by asafyev** [comment]
Thank you! That works perfectly!
