### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by Atihinen** [ombre42/jrobotremoteserver#29]
In https://code.google.com/p/jrobotremoteserver/ it's said that this project is under Apache 2.0 license, is this still true?

**Comment by ombre42** [comment]
Yes it is licensed under the Apache 2.0 license. This is documented in the pom.xml and in all the source files. I did not realize that I also need a LICENSE and NOTICE file at the root of the project.

**Comment by Atihinen** [comment]
Thanks! It really helps when dealing with corporations
