### ISSUE TITLE
Is possible to create some java class, on server, in the start of a teste and only that connection use that class.

### ISSUE THREAD

**Issue by augcampos** [ombre42/jrobotremoteserver#31]
In a scenario where I ave several tests using the same remote server, but I want to use different instances of the which class java, in the server  that I will call the methods in the test.

Thanks

**Comment by kormbrek-rally** [comment]
Yes this is possible. If you know ahead of time how many instances of your remote library that are required, you can add the library multiple times using different paths.

```
server.putLibrary("/foo1", new Foo());
server.putLibrary("/foo2", new Foo());
```

If you do not know how many instances you need, then you could create a small library for the simple purpose of controlling the remote server remotely. You could create a keyword that would put new library instances while the server is running also via putLibrary. I had considered building this functionality into the server, but was not sure if anyone would use it.

**Comment by augcampos** [comment]
Can I do "server.putLibrary("/foo1", new Foo());" with the server running?

**Comment by ombre42** [comment]
Yes. You can add libraries via putLibrary while the server is running. You can start the server with no libraries and add them all later if you wish.

**Comment by augcampos** [comment]
Great Thanks
