### ISSUE TITLE
If several robot test is calling a remote server can I id the cliente function caller?

### ISSUE THREAD

**Issue by augcampos** [ombre42/jrobotremoteserver#32]
In a scenario where I run several robot tests with call to the remote server
"Library     Remote		http://localhost:8270"

Can I ID the client caller in the function runner?

**Comment by kormbrek-rally** [comment]
The remote library API does not provide a way to identify the caller. There have been [discussions on this](https://github.com/robotframework/robotframework/issues/2084).
If you do not expect concurrent calls, you could implement a keyword to reset/initialize the library. If you need concurrency, then you could pass in some kind of ID as an extra argument to every call, but that is a pretty ugly workaround.

Always possible is somehow using multiple libraries on different paths. The libraries could be facades that all work with a singleton though if you need shared state across all callers.

**Comment by augcampos** [comment]
I try the parameter but is too much overload in the robot test :(
The idea is to have several of Robot test call the same RemoteServer :
1 - From the Robot test call Remote Server  SetupScenario()
2 - From the Robot test call Remote Server ProcessTest01(...
3 - From the Robot test call Remote Server ProcessTestN(...
4 - From the Robot test call Remote Server  DestroyScenario()
