### ISSUE TITLE
Can I run a construtor with a parameter in all keywords in a AnnotationLibrary

### ISSUE THREAD

**Issue by augcampos** [ombre42/jrobotremoteserver#33]
I need to pass some info(newid) in the constructor of all keywords in "com/example/keywords/*.class"

```
public class MyRemoteLibrary extends AnnotationLibrary {
    public MyRemoteLibrary() {
        // tell AnnotationLibrary where to find the keywords
        super("com/example/keywords/*.class");
    }
```

----
//com/example/keywords/EX1.JAVA
```
@RobotKeywords
public class SampleKeywords {
    public Long id;
    public SampleKeywords(final Long newId) {
        this.id = newId;
    }

  @RobotKeyword("SampleKeywordsGetID")
    public String SampleKeywordsGetID() {
        return this.id;
    }
```

**Comment by ombre42** [comment]
I believe the constructors need to be 
The way to accomplish what you want is to use the [@Autowired annotation.](https://github.com/robotframework/JavalibCore/wiki/AnnotationLibrary#autowired-annotation). Also if you want to take a shortcut and only will support once instance of your library, you could use a singleton.

These types of questions belong in [the user group](https://groups.google.com/forum/#!forum/robotframework-users), not an issue tracker.
