### ISSUE TITLE
Help needed to setup the jrobotremote server

### ISSUE THREAD

**Issue by rkommine** [ombre42/jrobotremoteserver#36]
Hi,
 
I need one help about configuring a Robot Remote Library server on a Linux machine. Using my windows machines Remote Library we will communicate to the Linux machine to use the keywords in the remote Library.

We are able to implement this in Python. 

But when we try to do this using Java jrobotserver as mentioned in GitHub, we are not able to do this. Could you please help me with one simple example. The below setup we try to setup Remote library using local machine 3002 port
[Robot_Remote_Lib.zip](https://github.com/ombre42/jrobotremoteserver/files/566150/Robot_Remote_Lib.zip)

Steps followed:

1.	Downloaded the robot remote server jar file(jrobotremoteserver-3.0-standalone.jar) with all dependencies from https://github.com/ombre42/jrobotremoteserver/releases
2.	Created the attached project.
3.	Copied the above jar file to Robot_Remote_Lib\Remote_Lib.
4.	Added the directory to CLASSPATH
5.	When I run the following command I am getting the below error:

C:\Users\rkommine>echo %CLASSPATH%
D:\userdata\rkommine\Desktop\Robot_Remote_Lib\Remote_Lib

C:\Users\rkommine>dir D:\userdata\rkommine\Desktop\Robot_Remote_Lib\Remote_Lib
 Volume in drive D is DATA
 Volume Serial Number is 2676-305E

 Directory of D:\userdata\rkommine\Desktop\Robot_Remote_Lib\Remote_Lib

11/02/2016  02:54 PM    <DIR>          .
11/02/2016  02:54 PM    <DIR>          ..
11/02/2016  02:54 PM         3,044,463 jrobotremoteserver-3.0-standalone.jar
               1 File(s)      3,044,463 bytes
               2 Dir(s)  23,769,686,016 bytes free

C:\Users\rkommine>java org.robotframework.remoteserver.RemoteServer --help
Error: Could not find or load main class org.robotframework.remoteserver.RemoteServer

Could you please let me know how to fix the error ? So that we can implement the Java library using Remote. 

Thanks in advance.

Regards,
Ramakrishna

**Comment by kormbrek-rally** [comment]
JARs need to be added to the classpath explicitly. Also your remote library needs to be on the classpath. If Remote_Lib is the root of your project and you used `classes` as the output folder from the compiler, your command might look like this:
```
SET CLASSPATH=D:\userdata\rkommine\Desktop\Robot_Remote_Lib\Remote_Lib\classes;D:\userdata\rkommine\Desktop\Robot_Remote_Lib\Remote_Libjrobotremoteserver-3.0-standalone.jar
```
If you have put your code into a JAR, you might do something like this:
```
SET CLASSPATH=D:\userdata\rkommine\Desktop\Robot_Remote_Lib\Remote_Lib\MyLibrary.jar;D:\userdata\rkommine\Desktop\Robot_Remote_Lib\Remote_Libjrobotremoteserver-3.0-standalone.jar
```
See https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html

**Comment by rkommine** [comment]
Hi,

Many thanks for the response. I have added the Jar file with folder name in Path. Now I am able to start the Jrobotremote server.

```
D:\userdata\rkommine\Desktop\Temp\Robot_Remote_Lib\Remote_Lib>set CLASSPATH=D:\userdata\rkommine\Desktop\Temp\Robot_Remo
te_Lib\Remote_Lib;D:\userdata\rkommine\Desktop\Temp\Robot_Remote_Lib\Remote_Lib\jrobotremoteserver-3.0-standalone.jar
```
`D:\userdata\rkommine\Desktop\Temp\Robot_Remote_Lib\Remote_Lib>java org.robotframework.remoteserver.RemoteServer --librar
y MyLibrary:/  --port 8270
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library MyLibrary.
2 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting
2 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
99 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}
1370 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:8270
1371 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 8270.` 

I have created a simple Java File. But I am not able to create any simple keyword in this. Could you please let me know how can I create the simple Keyword in this java library which will print the something as an argument from Robot test case.

I have attached the MyLibrary.java in the form of text file here.

[MyLibrary.txt](https://github.com/ombre42/jrobotremoteserver/files/568506/MyLibrary.txt)

Thanks in advance.

Regards,
Ramakrishna

**Comment by ombre42** [comment]
In the future please post to the [Robot Framework user guide](https://groups.google.com/forum/#!forum/robotframework-users) for help. This is an issue tracker.

In front of Mac at the moment so this is a little different. You use `set` instead of `export` and paths are separated by `;` instead of `:`, etc. I did use your java without modification.

Create test case like so:
```
*** Settings ***
Library    Remote    http://localhost:8270/    WITH NAME    MyLibrary

*** Test Cases ***
Hello World
    Create File    hello world
```
compilation:
```
➜  jr ls
MyLibrary.java                        jrobotremoteserver-3.0-standalone.jar
➜  jr javac MyLibrary.java
➜  jr ls
MyLibrary.class                       MyLibrary.java                        jrobotremoteserver-3.0-standalone.jar
```
Set the CLASSPATH and start the server:
```
➜  jr export CLASSPATH=.:./jrobotremoteserver-3.0-standalone.jar 
➜  jr java org.robotframework.remoteserver.RemoteServer --library MyLibrary --port 8270
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to library MyLibrary.
0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server starting
0 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
21 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.s.ServletContextHandler{/,null}
82 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:8270
82 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework remote server started on port 8270.
```
Then I ran the test case `robot HelloWorld.robot`
In the logs I see:
```
KEYWORD MyLibrary . Create File hello world
Start / End / Elapsed:	20161109 19:41:50.644 / 20161109 19:41:50.647 / 00:00:00.003
19:41:50.647	INFO	hello world
```

There are many ways to control the class path. There are many ways to build and package a Java project. For more complex libraries, I have an [example project](https://github.com/ombre42/jrobotremoteserver/tree/master/examples/AnnotationLibrary) using Maven that is out of date and a little wrong.

But packaging and class path stuff is not specific to jrobotremoteserver - so please do research if you want to learn more.

**Comment by rkommine** [comment]
Hi,

Many thanks for the valuable support. It was really helpful to understand how can I create the keywords in java & use the remote Library in Java.  I have tested above procedure & working now. I will explore more with the information provided. Next time I will post to the Robot Framework User community clarifications related to this. 

Thank you.
