### ISSUE TITLE
Built-in variable ${CURDIR} returns value from local machine and not from the remote

### ISSUE THREAD

**Issue by edsonharantes** [ombre42/jrobotremoteserver#41]
## Problem

I'm using the following code 

```
Library       Remote          http://192.168.0.101:8888/       WITH NAME     automation 

*** Test Cases ***
Test
    Log         ${CURDIR}
```

The log statement above does not return a path from the remote client but from my local machine. 

## Expected

${CURDIR} should be an absolute path from my client, not from my local machine.

I use a lot of resources files in my test cases so I need a way to reference them without changing the code.

**Comment by ombre42** [comment]
The remote server has no context of what is going on in the client side, even if it is running on the same machine. The remote library cannot access files on the client side unless they happen to be the same machine. If you have a bunch of files on the client side that need to go onto the remote, there are several ways of getting the files there such as SSHLibrary, invoking scp from Process or OperatingSystem libraries, etc. You could also add your own custom keyword that allows you to upload files.

`${CURDIR}` is a [Built-in variable](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#built-in-variables).

If you want to know what the current working directory is on the remote server, you would have to write a keyword in your library to make it available. Something like,
```
public String getWorkingDirectory() {
    return System.getProperty("user.dir")
}
```

And in your test,

```
${remote_cwd}    Get Working Directory
```

**Comment by edsonharantes** [comment]
Thank you very much for your response, I created a config file with a global variable ${root} and them I'm passing the root value in the script that I use to execute test cases with the correct path.
