### ISSUE TITLE
Upgrade project to Jetty 9.x

### ISSUE THREAD

**Issue by shan-96** [ombre42/jrobotremoteserver#44]
Hi @ombre42 

My organisation uses this project to invoke robot server. However when we upgraded to jetty 9.x from 7.x we found that the server doesn't start. This is because jetty v9.x doesn't include the `SelectChannelConnector`class as they have moved away from HTTP/1.x

I feel that `SelectChannelConnector`can be replaced by `ServerConnector` in `RemoteServer.java` and other particular location with minor refactor. I am also working on this after the holiday, but do you think this is feasible and we can package this into a release and ship to maven?

Thank you

**Comment by shan-96** [comment]
I see that @Hi-Fi has pointed me to the correct pull request. Is the same released to maven central repo?

Thanks

**Comment by Hi-Fi** [comment]
> I see that @Hi-Fi has pointed me to the correct pull request. Is the same released to maven central repo?
> 
> Thanks

That's just PR, nothing more. There's no (at least Github reporting) automatic deployments of the SNAPSHOTs or releases, so PR has to be handled first, merged and published.

**Comment by shan-96** [comment]
I have forked this PR and other custom changes to my local repo. This project thread is dead.
